### PR TITLE
fix: sorting the matches list in ascending order of date

### LINKED ISSUE #80: Area VIP - Next Matches block should render the links and price from the API response
Currently the links in the next matches block do not take to the appropriate location. We need to update the links with the API response. 

Also the price is hard coded in the block. That should also be rendered from the API response

The matches block in different VIP Areas show different matches. The API should provide the support for that as well.

### PR DESCRIPTION
**Pull request by vdua**
- using the new information in the API
- fixing filter name from toDate to endDate

Fixes #80 

Test URLs:
- Before: https://main--realmadrid--hlxsites.hlx.page/sites/area-vip
- After: https://matches-new--realmadrid--hlxsites.hlx.page/sites/area-vip

### CODE REVIEW

File: sites/blocks/matches/matches.js [hunk 1]
```diff
@@ -276,14 +281,15 @@ export default async function decorate(block) {
   const { sport = '' } = config;
   let items = [];
   try {
-    // todo: add params fromDate endDate
     if (aemGqEndpoint && API[sport.toLowerCase()]) {
-      const filter = `fromDate=${new Date().toISOString()};toDate=${SEASON_END_DATE}`;
+      const filter = `${FILTERS.fromDate}=${new Date('2023-09-20').toISOString()};${FILTERS.endDate}=${SEASON_END_DATE}`;
```
Comment (vdua) [inline sites/blocks/matches/matches.js:285]: this is temporary, to demonstrate the UI. Will switch to today's date before merging.

**Review by chicharr — APPROVED** [review]
LGTM. 
Just one comment, in Desktop the team shield image is a bit squashed
